# Importando bibliotecas

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

# Importando dados

In [2]:
df = pd.read_csv('../../data/raw/exames.csv', )
df

,id,diagnostico,exame_1,exame_2,exame_3,exame_4,exame_5,exame_6,exame_7,exame_8,...,exame_24,exame_25,exame_26,exame_27,exame_28,exame_29,exame_30,exame_31,exame_32,exame_33
0,842302,M,17.99,10.38,122.80,103.78,1001.0,0.11840,0.27760,0.30010,...,184.60,2019.0,0.16220,0.66560,0.7119,0.786,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,103.78,1326.0,0.08474,0.07864,0.08690,...,158.80,1956.0,0.12380,0.18660,0.2416,0.786,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,103.78,1203.0,0.10960,0.15990,0.19740,...,152.50,1709.0,0.14440,0.42450,0.4504,0.786,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,103.78,386.1,0.14250,0.28390,0.24140,...,98.87,567.7,0.20980,0.86630,0.6869,0.786,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,103.78,1297.0,0.10030,0.13280,0.19800,...,152.20,1575.0,0.13740,0.20500,0.4000,0.786,0.1625,0.2364,0.07678,0.854454
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,103.78,1479.0,0.11100,0.11590,0.24390,...,166.10,2027.0,0.14100,0.21130,0.4107,0.786,0.2216,0.2060,0.07115,0.158771
565,926682,M,20.13,28.25,131.20,103.78,1261.0,0.09780,0.10340,0.14400,...,155.00,1731.0,0.11660,0.19220,0.3215,0.786,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.30,103.78,858.1,0.08455,0.10230,0.09251,...,126.70,1124.0,0.11390,0.30940,0.3403,0.786,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.10,103.78,1265.0,0.11780,0.27700,0.35140,...,184.60,1821.0,0.16500,0.86810,0.9387,0.786,0.2650,0.4087,0.12400,NaN
568,92751,B,7.76,24.54,47.92,103.78,181.0,0.05263,0.04362,0.00000,...,59.16,268.6,0.08996,0.06444,0.0000,0.786,0.0000,0.2871,0.07039,NaN

# Analises

## Informacoes das variaveis

In [3]:
# identificando quantidade de valores nao nulos e tipos das variaveis
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 35 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           569 non-null    int64
 1   diagnostico  569 non-null    str
 2   exame_1      569 non-null    float64
 3   exame_2      569 non-null    float64
 4   exame_3      569 non-null    float64
 5   exame_4      569 non-null    float64
 6   exame_5      569 non-null    float64
 7   exame_6      569 non-null    float64
 8   exame_7      569 non-null    float64
 9   exame_8      569 non-null    float64
 10  exame_9      569 non-null    float64
 11  exame_10     569 non-null    float64
 12  exame_11     569 non-null    float64
 13  exame_12     569 non-null    float64
 14  exame_13     569 non-null    float64
 15  exame_14     569 non-null    float64
 16  exame_15     569 non-null    float64
 17  exame_16     569 non-null    float64
 18  exame_17     569 non-null    float64
 19  exame_18     569 non-null    float64
 20  exame_19     569 non-null    float64
 21  exame_20     569 non-null    float64
 22  exame_21     569 non-null    float64
 23  exame_22     569 non-null    float64
 24  exame_23     569 non-null    float64
 25  exame_24     569 non-null    float64
 26  exame_25     569 non-null    float64
 27  exame_26     569 non-null    float64
 28  exame_27     569 non-null    float64
 29  exame_28     569 non-null    float64
 30  exame_29     569 non-null    float64
 31  exame_30     569 non-null    float64
 32  exame_31     569 non-null    float64
 33  exame_32     569 non-null    float64
 34  exame_33     150 non-null    float64
dtypes: float64(33), int64(1), str(1)
memory usage: 155.7 KB

In [10]:
# valores unicos da variavel categorica

df['diagnostico'].value_counts()

diagnostico
B    357
M    212
Name: count, dtype: int64

## Identificando variaveis com valores unicos

In [4]:
# Identifica colunas com apenas um valor único
colunas_unicas = df.columns[df.nunique() == 1]
display(colunas_unicas)

Index(['exame_4', 'exame_29'], dtype='str')

In [5]:
# removendo variaveis com valores unicos
df = df.drop(columns={'exame_4', 'exame_29'}).copy()

## Valores ausentes

### Anotacoes

- Apenas uma variavel possui valores NaN, seria a variavel: exames_33
- Foram identificados 419 valores NaN nessa variavel
- Temos 569 registros totais na base e 419 registros NaN para variavel exames_33
    - Representando: (419/569)*100 = 73% dos dados
    - Devido porcentagem alta, nao avaliaria variavel e a descartaria, documentando neste projeto o motivo.

In [6]:
df.isna().sum()

id               0
diagnostico      0
exame_1          0
exame_2          0
exame_3          0
exame_5          0
exame_6          0
exame_7          0
exame_8          0
exame_9          0
exame_10         0
exame_11         0
exame_12         0
exame_13         0
exame_14         0
exame_15         0
exame_16         0
exame_17         0
exame_18         0
exame_19         0
exame_20         0
exame_21         0
exame_22         0
exame_23         0
exame_24         0
exame_25         0
exame_26         0
exame_27         0
exame_28         0
exame_30         0
exame_31         0
exame_32         0
exame_33       419
dtype: int64

In [7]:
# removendo variavel com maior representacao de valores ausentes 
df = df.drop(columns={'exame_33'}).copy()

## Identificando variaveis numericas

In [8]:
# selecionando variaveis numericas de df
df_num = df.select_dtypes(include='number')
df_num

,id,exame_1,exame_2,exame_3,exame_5,exame_6,exame_7,exame_8,exame_9,exame_10,...,exame_22,exame_23,exame_24,exame_25,exame_26,exame_27,exame_28,exame_30,exame_31,exame_32
0,842302,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,842517,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,84300903,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,84348301,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,84358402,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,926682,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,926954,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,927241,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,92751,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

## Heatmap de correlacao das variaveis

In [9]:
# criando matriz de correlacao das variaveis numericas
matriz_corr = df_num.corr()

# criando grafico de correlacao de variaveis com matriz de correlacao calculada
fig_heatmap = px.imshow(
    matriz_corr,
    title='Heatmap de correlacao das variaveis',
    text_auto=True,
    height=1200
)

fig_heatmap.show()