# Anotacoes


- Remocao da variavel "exame_4" e "exame_29"
    - Motivo:
        - Variavel com apenas um valor unico
        - Nao eh interessante manter pois nao agregara em nada para o modelo ML
        - Aprenda: modelos ML descartam automaticamente variaveis que nao possuem variacao em seus valores (variaveis com um valor unico), nao agrega em nada para o aprendizado do modelo.

- Remocao da variavel "exame_33"
    - Motivo: 
        - 419 de 569 valores sao ausentes (NaN), representando 73% dos dados.
        - Devido alta representacao, nao sera necessario analise pois variavel nao sera util.

# Importando bibliotecas

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from numpy import random

# Importando dados

In [2]:
df = pd.read_csv('../../data/raw/exames.csv', )
df

,id,diagnostico,exame_1,exame_2,exame_3,exame_4,exame_5,exame_6,exame_7,exame_8,...,exame_24,exame_25,exame_26,exame_27,exame_28,exame_29,exame_30,exame_31,exame_32,exame_33
0,842302,M,17.99,10.38,122.80,103.78,1001.0,0.11840,0.27760,0.30010,...,184.60,2019.0,0.16220,0.66560,0.7119,0.786,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,103.78,1326.0,0.08474,0.07864,0.08690,...,158.80,1956.0,0.12380,0.18660,0.2416,0.786,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,103.78,1203.0,0.10960,0.15990,0.19740,...,152.50,1709.0,0.14440,0.42450,0.4504,0.786,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,103.78,386.1,0.14250,0.28390,0.24140,...,98.87,567.7,0.20980,0.86630,0.6869,0.786,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,103.78,1297.0,0.10030,0.13280,0.19800,...,152.20,1575.0,0.13740,0.20500,0.4000,0.786,0.1625,0.2364,0.07678,0.854454
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,103.78,1479.0,0.11100,0.11590,0.24390,...,166.10,2027.0,0.14100,0.21130,0.4107,0.786,0.2216,0.2060,0.07115,0.158771
565,926682,M,20.13,28.25,131.20,103.78,1261.0,0.09780,0.10340,0.14400,...,155.00,1731.0,0.11660,0.19220,0.3215,0.786,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.30,103.78,858.1,0.08455,0.10230,0.09251,...,126.70,1124.0,0.11390,0.30940,0.3403,0.786,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.10,103.78,1265.0,0.11780,0.27700,0.35140,...,184.60,1821.0,0.16500,0.86810,0.9387,0.786,0.2650,0.4087,0.12400,NaN
568,92751,B,7.76,24.54,47.92,103.78,181.0,0.05263,0.04362,0.00000,...,59.16,268.6,0.08996,0.06444,0.0000,0.786,0.0000,0.2871,0.07039,NaN

# Tratando dados

In [3]:
# removendo variaveis nao interessantes
df = df.drop(columns={'exame_4', 'exame_29', 'exame_33'}).copy()

In [4]:
df

,id,diagnostico,exame_1,exame_2,exame_3,exame_5,exame_6,exame_7,exame_8,exame_9,...,exame_22,exame_23,exame_24,exame_25,exame_26,exame_27,exame_28,exame_30,exame_31,exame_32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

# Separando dados para train test de modelo

In [5]:
# definindo SEED para reprodutibilidade do train_test_split
SEED = 123143
random.seed(SEED)

# criando variaveis para train_test_split
# valores_exames = toda a base df exceto as variaveis 'id' e 'diagnostico'. Essa base representara nossas features
valores_exames = df.drop(columns={'id', 'diagnostico'}).copy()
# diagnostico = apenas a coluna 'diagnostico' da base de dados, ela sera nosso target
diagnostico = df[['diagnostico']].copy()

# separando os dados para train e test do modelo
treino_x, teste_x, treino_y, teste_y = train_test_split(valores_exames,
                                                        diagnostico, 
                                                        test_size=0.3)

# visualizando a separacao dos dados
display(treino_x)
display(teste_x)
display(treino_y)
display(teste_y)

# salvando bases treino_x, teste_x, treino_y e teste_y
treino_x.to_csv('../../data/processed/treino_x.csv', index=False)
teste_x.to_csv('../../data/processed/teste_x.csv', index=False)
treino_y.to_csv('../../data/processed/treino_y.csv', index=False)
teste_y.to_csv('../../data/processed/teste_y.csv', index=False)

,exame_1,exame_2,exame_3,exame_5,exame_6,exame_7,exame_8,exame_9,exame_10,exame_11,...,exame_22,exame_23,exame_24,exame_25,exame_26,exame_27,exame_28,exame_30,exame_31,exame_32
268,12.87,16.21,82.38,512.2,0.09425,0.06219,0.03900,0.016150,0.2010,0.05769,...,13.90,23.64,89.27,597.5,0.12560,0.1808,0.19920,0.05780,0.3604,0.07062
422,11.61,16.02,75.46,408.2,0.10880,0.11680,0.07097,0.044970,0.1886,0.06320,...,12.64,19.67,81.93,475.7,0.14150,0.2170,0.23020,0.11050,0.2787,0.07427
168,17.47,24.68,116.10,984.6,0.10490,0.16030,0.21590,0.104300,0.1538,0.06365,...,23.14,32.33,155.30,1660.0,0.13760,0.3830,0.48900,0.17210,0.2160,0.09300
501,13.82,24.49,92.33,595.9,0.11620,0.16810,0.13570,0.067590,0.2275,0.07237,...,16.01,32.94,106.00,788.0,0.17940,0.3966,0.33810,0.15210,0.3651,0.11830
563,20.92,25.09,143.00,1347.0,0.10990,0.22360,0.31740,0.147400,0.2149,0.06879,...,24.29,29.41,179.10,1819.0,0.14070,0.4186,0.65990,0.25420,0.2929,0.09873
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,14.62,24.02,94.57,662.7,0.08974,0.08606,0.03102,0.029570,0.1685,0.05866,...,16.11,29.11,102.90,803.7,0.11150,0.1766,0.09189,0.06946,0.2522,0.07246
144,10.75,14.97,68.26,355.3,0.07793,0.05139,0.02251,0.007875,0.1399,0.05688,...,11.95,20.72,77.79,441.2,0.10760,0.1223,0.09755,0.03413,0.2300,0.06769
133,15.71,13.93,102.00,761.7,0.09462,0.09462,0.07135,0.059330,0.1816,0.05723,...,17.50,19.25,114.30,922.8,0.12230,0.1949,0.17090,0.13740,0.2723,0.07071
282,19.40,18.18,127.20,1145.0,0.10370,0.14420,0.16260,0.094640,0.1893,0.05892,...,23.79,28.65,152.40,1628.0,0.15180,0.3749,0.43160,0.22520,0.3590,0.07787
157,16.84,19.46,108.40,880.2,0.07445,0.07223,0.05150,0.027710,0.1844,0.05268,...,18.22,28.07,120.30,1032.0,0.08774,0.1710,0.18820,0.08436,0.2527,0.05972

,exame_1,exame_2,exame_3,exame_5,exame_6,exame_7,exame_8,exame_9,exame_10,exame_11,...,exame_22,exame_23,exame_24,exame_25,exame_26,exame_27,exame_28,exame_30,exame_31,exame_32
550,10.860,21.48,68.51,360.5,0.07431,0.04227,0.00000,0.000000,0.1661,0.05948,...,11.660,24.77,74.08,412.3,0.1001,0.07348,0.00000,0.00000,0.2458,0.06592
405,10.940,18.59,70.39,370.0,0.10040,0.07460,0.04944,0.029320,0.1486,0.06615,...,12.400,25.58,82.76,472.4,0.1363,0.16440,0.14120,0.07887,0.2251,0.07732
239,17.460,39.28,113.40,920.6,0.09812,0.12980,0.14170,0.088110,0.1809,0.05966,...,22.510,44.87,141.20,1408.0,0.1365,0.37350,0.32410,0.20660,0.2853,0.08496
76,13.530,10.94,87.91,559.2,0.12910,0.10470,0.06877,0.065560,0.2403,0.06641,...,14.080,12.49,91.36,605.5,0.1451,0.13790,0.08539,0.07407,0.2710,0.07191
458,13.000,25.13,82.61,520.2,0.08369,0.05073,0.01206,0.017620,0.1667,0.05449,...,14.340,31.88,91.06,628.5,0.1218,0.10930,0.04462,0.05921,0.2306,0.06291
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,12.830,15.73,82.89,506.9,0.09040,0.08269,0.05835,0.030780,0.1705,0.05913,...,14.090,19.35,93.22,605.8,0.1326,0.26100,0.34760,0.09783,0.3006,0.07802
328,16.270,20.71,106.90,813.7,0.11690,0.13190,0.14780,0.084880,0.1948,0.06277,...,19.280,30.38,129.80,1121.0,0.1590,0.29470,0.35970,0.15830,0.3103,0.08200
412,9.397,21.68,59.75,268.8,0.07969,0.06053,0.03735,0.005128,0.1274,0.06724,...,9.965,27.99,66.61,301.0,0.1086,0.18870,0.18680,0.02564,0.2376,0.09206
235,14.030,21.25,89.79,603.4,0.09070,0.06945,0.01462,0.018960,0.1517,0.05835,...,15.330,30.28,98.27,715.5,0.1287,0.15130,0.06231,0.07963,0.2226,0.07617
286,11.940,20.76,77.87,441.0,0.08605,0.10110,0.06574,0.037910,0.1588,0.06766,...,13.240,27.29,92.20,546.1,0.1116,0.28130,0.23650,0.11550,0.2465,0.09981

    diagnostico
268           B
422           B
168           M
501           M
563           M
..          ...
90            B
144           B
133           B
282           M
157           B

[398 rows x 1 columns]

    diagnostico
550           B
405           B
239           M
76            B
458           B
..          ...
475           B
328           M
412           B
235           B
286           B

[171 rows x 1 columns]